services:
  db:
    image: pgvector/pgvector:pg18
    container_name: opsintel-db

    environment:
      POSTGRES_USER: opsintel
      POSTGRES_PASSWORD: opsintel
      POSTGRES_DB: opsintel

    ports:
      - "5432:5432"

    volumes:
      - opsintel_postgres:/var/lib/postgresql

volumes:
  opsintel_postgres:
